"use strict";
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
$('#year').textContent=new Date().getFullYear();let toastTimer;
function toast(t){$('#toast').textContent=t;$('#toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').classList.remove('show'),3500)}
$$('[data-copy]').forEach(b=>b.onclick=async()=>{try{await navigator.clipboard.writeText(b.dataset.copy);toast(b.dataset.copyKind==='game'?'In-game command copied. Paste it into Rust chat.':'Connection command copied. Paste it into Rust with F1.')}catch{toast(b.dataset.copyKind==='game'?'Copy unavailable. Select the command and paste it into Rust chat.':'Copy unavailable. Open Join the server to select the command.')}});
$$('[data-dialog]').forEach(b=>b.onclick=()=>{const d=document.getElementById(b.dataset.dialog);d.showModal();if(d.id==='mapDialog')mapUpdate()});$$('dialog').forEach(d=>{d.querySelector('.close').onclick=()=>d.close();d.addEventListener('click',e=>{if(e.target!==d)return;const r=d.getBoundingClientRect();if(e.clientX<r.left||e.clientX>r.right||e.clientY<r.top||e.clientY>r.bottom)d.close()})});
const pages=['home','server','news','wildlife','farming','raid','cctv','cards','servers','pve','pve-map','pve-rules','pve-plugins','pve-commands','weapons','vehicles'];const names={home:'OVERVIEW',server:'OUR SERVER',news:'WHAT’S NEW',wildlife:'WILDLIFE',farming:'FARMING',raid:'RAID CALCULATOR',cctv:'CCTV CODES',cards:'MONUMENTS & CARDS',servers:'AUSSIE MAFIA SERVERS',pve:'AUSSIE MAFIA PVE 5X','pve-map':'ORI ISLAND MAP','pve-rules':'PVE RULES','pve-plugins':'PVE PLUGINS & FEATURES','pve-commands':'IN-GAME COMMANDS',weapons:'RUST WEAPONS',vehicles:'RUST VEHICLES'};
function route(){let p=location.hash.slice(1);if(!pages.includes(p))p='home';const pveMode=p==='pve'||p.startsWith('pve-');$$('.page').forEach(el=>el.hidden=el.id!=='page-'+p);$$('[data-page]').forEach(a=>{const active=a.dataset.page===p||(a.dataset.page==='pve'&&pveMode);a.classList.toggle('active',active);if(active)a.setAttribute('aria-current','page');else a.removeAttribute('aria-current')});$('#pageLabel').textContent=names[p];document.title='Aussie Mafia | '+names[p];const mode=$('#modeLabel'),join=$('#headerJoin');if(mode)mode.textContent=pveMode?'PVE · 5X MODDED':'VANILLA PVP';if(join){join.dataset.dialog=pveMode?'connectPve':'connect';join.innerHTML=pveMode?'JOIN PVE 5X <b>+</b>':'JOIN THE SERVER <b>+</b>'}scrollTo({top:0,behavior:'instant'})}addEventListener('hashchange',route);route();
const video=$('#worldVideo'),motionButton=$('#motionToggle'),reduce=matchMedia('(prefers-reduced-motion: reduce)');let motionOff=reduce.matches;
function syncMotion(){motionButton.textContent=motionOff?'▶ Play background':'Ⅱ Pause background';$('#mobileMotion').textContent=motionOff?'Play background':'Pause background';motionButton.setAttribute('aria-pressed',String(motionOff));if(motionOff)video.pause();else video.play().catch(()=>{motionOff=true;motionButton.textContent='▶ Play background';motionButton.setAttribute('aria-pressed','true')})}motionButton.onclick=()=>{motionOff=!motionOff;syncMotion()};$('#mobileMotion').onclick=motionButton.onclick;reduce.addEventListener('change',()=>{motionOff=reduce.matches;syncMotion()});syncMotion();
$$('[data-animal]').forEach(b=>{b.setAttribute('aria-pressed',String(b.classList.contains('active')));b.onclick=()=>{$$('[data-animal]').forEach(x=>{x.classList.toggle('active',x===b);x.setAttribute('aria-pressed',String(x===b))});$$('[data-group]').forEach(a=>a.hidden=b.dataset.animal!=='all'&&b.dataset.animal!==a.dataset.group)}});
const farmData={livestock:{label:'YOUR FIRST HERD',title:'Make room<br>for livestock.',text:'New gates and fences help contain animals. Grown livestock can be sold to a stable vendor; genetics influence offers.'},dairy:{label:'FROM THE HERD TO THE KITCHEN',title:'Milk, cream<br>& new recipes.',text:'Refrigerate milk for four hours to unlock skimming. Milk and cream can modify tea effects.'},fuel:{label:'NOTHING GOES TO WASTE',title:'Organic matter.<br>Useful fuel.',text:'The Biofuel Generator turns organic matter into low-grade fuel. It needs periodic hand stirring.'}};
const farmTabs=$$('[data-farm]');function pickFarm(b){const d=farmData[b.dataset.farm];farmTabs.forEach(t=>{t.setAttribute('aria-selected',String(t===b));t.tabIndex=t===b?0:-1});$('#farmPanel').setAttribute('aria-labelledby',b.id);$('#farmLabel').textContent=d.label;$('#farmTitle').innerHTML=d.title;$('#farmText').textContent=d.text}farmTabs.forEach((b,i)=>{b.onclick=()=>pickFarm(b);b.onkeydown=e=>{let n;if(['ArrowRight','ArrowDown'].includes(e.key))n=(i+1)%farmTabs.length;if(['ArrowLeft','ArrowUp'].includes(e.key))n=(i+farmTabs.length-1)%farmTabs.length;if(e.key==='Home')n=0;if(e.key==='End')n=farmTabs.length-1;if(n!==undefined){e.preventDefault();pickFarm(farmTabs[n]);farmTabs[n].focus()}}});
let zoom=1,panX=0,panY=0,drag=null;const stage=$('#mapStage'),layer=$('#mapLayer');function mapUpdate(){const maxX=stage.clientWidth*(zoom-1)/2,maxY=stage.clientHeight*(zoom-1)/2;panX=Math.max(-maxX,Math.min(maxX,panX));panY=Math.max(-maxY,Math.min(maxY,panY));layer.style.transform=`translate(${panX}px,${panY}px) scale(${zoom})`;$('#zoomValue').textContent=Math.round(zoom*100)+'%';$('#zoomOut').disabled=zoom<=1;$('#zoomIn').disabled=zoom>=3;stage.style.touchAction=zoom>1?'none':'pan-y'}function changeZoom(delta){zoom=Math.max(1,Math.min(3,zoom+delta));mapUpdate()}$('#zoomIn').onclick=()=>changeZoom(.5);$('#zoomOut').onclick=()=>changeZoom(-.5);$('#mapReset').onclick=()=>{zoom=1;panX=panY=0;mapUpdate()};stage.addEventListener('pointerdown',e=>{if(e.target.closest('button')||zoom===1)return;drag={x:e.clientX,y:e.clientY,panX,panY};stage.setPointerCapture(e.pointerId)});stage.addEventListener('pointermove',e=>{if(!drag)return;panX=drag.panX+e.clientX-drag.x;panY=drag.panY+e.clientY-drag.y;mapUpdate()});['pointerup','pointercancel','lostpointercapture'].forEach(type=>stage.addEventListener(type,()=>drag=null));stage.addEventListener('keydown',e=>{if(e.target!==stage)return;if(e.key==='+'||e.key==='='){changeZoom(.5);e.preventDefault()}else if(e.key==='-'){changeZoom(-.5);e.preventDefault()}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&zoom>1){panX+=e.key==='ArrowLeft'?30:e.key==='ArrowRight'?-30:0;panY+=e.key==='ArrowUp'?30:e.key==='ArrowDown'?-30:0;mapUpdate();e.preventDefault()}});new ResizeObserver(mapUpdate).observe(stage);mapUpdate();

async function refreshPlayers(){const refresh=$('#refresh');if(refresh.disabled)return;refresh.disabled=true;$('#status').textContent='Updating…';try{const r=await fetch('https://cdn.battlemetrics.com/b/horizontal500x80px/40453506.html',{signal:AbortSignal.timeout(12000)});if(!r.ok)throw Error();const doc=new DOMParser().parseFromString(await r.text(),'text/html');if(doc.querySelector('#server-name a')?.getAttribute('href')!=='https://www.battlemetrics.com/servers/rust/40453506')throw Error();const match=doc.querySelector('#server-players')?.textContent.trim().match(/^(\d+)\s*\/\s*(\d+)$/);if(!match||+match[2]<1)throw Error();$('#players').textContent=Number(match[1])+' / '+Number(match[2]);$('#status').textContent='Player count · may be delayed';$('.dock-status').style.background='#94c68b'}catch{$('#players').textContent='— / —';$('#status').textContent='Count unavailable';$('.dock-status').style.background='#8493a3'}finally{refresh.disabled=false;const cardPlayers=$('#vanilla-directory-players'),cardStatus=$('#vanilla-directory-status');if(cardPlayers)cardPlayers.textContent=$('#players').textContent;if(cardStatus)cardStatus.textContent=$('#status').textContent}}
$('#refresh').onclick=refreshPlayers;refreshPlayers();setInterval(()=>{if(!document.hidden)refreshPlayers()},300000);

const pveStatusWidget=$('#pve-status-widget');
function readPveWidgetPlayers(){
 const section=pveStatusWidget?.shadowRoot?.querySelector('.serverCard-section--players');
 const value=section?.querySelector('.text-3xl')?.textContent||'';
 const match=value.replace(/\s+/g,' ').trim().match(/^(\d+)\s*\/\s*(\d+)$/);
 return match&&+match[2]>0?match:null;
}
let pveRefreshInFlight=false;
async function refreshPvePlayers(){
 const cardPlayers=$('#pve-directory-players'),cardStatus=$('#pve-directory-status');
 if(!cardPlayers||!cardStatus||pveRefreshInFlight)return;
 pveRefreshInFlight=true;
 cardStatus.textContent='Updating…';
 try{
  let match;
  const until=Date.now()+30000;
  while(Date.now()<until){
   match=readPveWidgetPlayers();
   if(match)break;
   await new Promise(resolve=>setTimeout(resolve,500));
  }
  if(!match)throw Error();
  cardPlayers.textContent=match[1]+' / '+match[2];
  cardStatus.textContent='Player count · may be delayed';
 }catch{
  cardPlayers.textContent='— / —';
  cardStatus.textContent='Count unavailable';
 }finally{pveRefreshInFlight=false}
}
refreshPvePlayers();setTimeout(refreshPvePlayers,15000);setInterval(()=>{if(!document.hidden)refreshPvePlayers()},300000);

// Background music supplied by the site owner. Try on load, then retry on a user gesture if blocked.
const backgroundMusic=document.getElementById('backgroundMusic');
backgroundMusic.volume=0.3;
let musicStarting=false;
const musicGestures=['pointerdown','click','touchend','keydown'];
function stopMusicRetries(){musicGestures.forEach(type=>document.removeEventListener(type,startBackgroundMusic,true));}
async function startBackgroundMusic(){
 if(musicStarting||!backgroundMusic.paused)return;
 musicStarting=true;
 try{await backgroundMusic.play();stopMusicRetries();}catch{/* Browser requires a user gesture; leave listeners ready. */}
 finally{musicStarting=false;}
}
backgroundMusic.addEventListener('playing',stopMusicRetries);
musicGestures.forEach(type=>document.addEventListener(type,startBackgroundMusic,{capture:true,passive:true}));
startBackgroundMusic();


// Interactive Ori Island map
let pveZoom=1,pvePanX=0,pvePanY=0,pveDrag=null;
const pveStage=$('#pveMapStage'),pveLayer=$('#pveMapLayer');
function pveMapUpdate(){
 if(!pveStage||!pveLayer)return;
 const maxX=pveStage.clientWidth*(pveZoom-1)/2,maxY=pveStage.clientHeight*(pveZoom-1)/2;
 pvePanX=Math.max(-maxX,Math.min(maxX,pvePanX));pvePanY=Math.max(-maxY,Math.min(maxY,pvePanY));
 pveLayer.style.transform=`translate(${pvePanX}px,${pvePanY}px) scale(${pveZoom})`;
 const value=$('#pveZoomValue');if(value)value.textContent=Math.round(pveZoom*100)+'%';
 const out=$('#pveZoomOut'),inc=$('#pveZoomIn');if(out)out.disabled=pveZoom<=1;if(inc)inc.disabled=pveZoom>=4;
 pveStage.style.touchAction=pveZoom>1?'none':'pan-y';
}
function pveChangeZoom(delta){pveZoom=Math.max(1,Math.min(4,pveZoom+delta));pveMapUpdate()}
if(pveStage){
 $('#pveZoomIn').onclick=()=>pveChangeZoom(.5);$('#pveZoomOut').onclick=()=>pveChangeZoom(-.5);
 $('#pveMapReset').onclick=()=>{pveZoom=1;pvePanX=pvePanY=0;pveMapUpdate()};
 pveStage.addEventListener('pointerdown',e=>{if(e.target.closest('button')||pveZoom===1)return;pveDrag={x:e.clientX,y:e.clientY,panX:pvePanX,panY:pvePanY};pveStage.setPointerCapture(e.pointerId)});
 pveStage.addEventListener('pointermove',e=>{if(!pveDrag)return;pvePanX=pveDrag.panX+e.clientX-pveDrag.x;pvePanY=pveDrag.panY+e.clientY-pveDrag.y;pveMapUpdate()});
 ['pointerup','pointercancel','lostpointercapture'].forEach(type=>pveStage.addEventListener(type,()=>pveDrag=null));
 pveStage.addEventListener('keydown',e=>{if(e.target!==pveStage)return;if(e.key==='+'||e.key==='='){pveChangeZoom(.5);e.preventDefault()}else if(e.key==='-'){pveChangeZoom(-.5);e.preventDefault()}else if(['ArrowLeft','ArrowRight','ArrowUp','ArrowDown'].includes(e.key)&&pveZoom>1){pvePanX+=e.key==='ArrowLeft'?30:e.key==='ArrowRight'?-30:0;pvePanY+=e.key==='ArrowUp'?30:e.key==='ArrowDown'?-30:0;pveMapUpdate();e.preventDefault()}});
 new ResizeObserver(pveMapUpdate).observe(pveStage);pveMapUpdate();
}

function filterCards(stage){$$('[data-card-stage]').forEach(x=>x.hidden=stage!=='all'&&x.dataset.cardStage!==stage);$$('[data-card]').forEach(x=>{x.classList.toggle('active',x.dataset.card===stage);x.setAttribute('aria-pressed',String(x.dataset.card===stage))})}$$('[data-card]').forEach(x=>x.onclick=()=>filterCards(x.dataset.card));$$('[data-card-filter]').forEach(x=>x.onclick=()=>filterCards(x.dataset.cardFilter));


/* Base Building Guides: 20 practical Rust layouts with estimate calculator. */
(()=>{
const baseData=[
['SMALL','STARTER 2X1','Solo / Duo','wood 2,200 · stone 4,500 · metal 350','Expand quickly; add a triangle airlock before storing loot.','rust 2x1 starter base build 2026'],
['SMALL','COMPACT 2X2','Solo / Duo','wood 3,100 · stone 7,000 · metal 500','The front door is predictable; offset the entrance and protect the TC.','rust compact 2x2 solo duo base build'],
['SMALL','TRIANGLE AIRLOCK','Solo / Duo','wood 2,800 · stone 5,800 · metal 450','A single door path is easy to read; use a second airlock or bunker entrance.','rust triangle airlock starter base build'],
['SMALL','MINI BUNKER','Solo / Duo','wood 3,600 · stone 8,500 · metal 650','Bunker seal and roof hatch are the critical points; never leave the seal open.','rust solo bunker base build 2026'],
['SMALL','SOLO HIDDEN LOOT','Solo','wood 2,000 · stone 5,000 · metal 400','Small footprint is easy to splash; spread valuables through separate compartments.','rust solo hidden loot base build'],
['MEDIUM','3X3 HONEYCOMB','Duo / Trio','wood 4,800 · stone 18,000 · metal 1,200','Roof access and wide honeycomb gaps can expose the core.','rust 3x3 honeycomb base build duo trio'],
['MEDIUM','COMPOUND 2X2','Duo / Trio','wood 6,500 · stone 21,000 · metal 1,500','Outer compound is not the core; protect gates and keep turrets off one power line.','rust compound 2x2 base build trio'],
['MEDIUM','SPLIT-CORE 3X2','Duo / Trio','wood 5,500 · stone 16,500 · metal 1,400','Two cores slow raiders, but weak roof stability can create a shortcut.','rust split core 3x2 base build'],
['MEDIUM','MOUNTAIN SHELL','Duo / Trio','wood 4,500 · stone 15,000 · metal 1,000','Terrain can hide the rear, but cliff exposure and roof access remain vulnerable.','rust mountain base build duo trio'],
['MEDIUM','FARMHOUSE DEFENDER','Duo / Trio','wood 7,000 · stone 19,000 · metal 1,300','Large windows and farm openings reveal the loot path; seal the living area.','rust farmhouse base build pvp'],
['LARGE','4X4 CORE','Trio / Quad','wood 7,500 · stone 30,000 · metal 2,400','A square footprint needs layered roof protection or raiders can top-down the core.','rust 4x4 core base build trio quad'],
['LARGE','OFFSET HONEYCOMB','Trio / Quad','wood 8,000 · stone 34,000 · metal 2,800','Offset walls confuse pathing, but exposed jump-ups can undo the advantage.','rust offset honeycomb base build'],
['LARGE','COMPOUND TOWER','Trio / Quad','wood 12,000 · stone 40,000 · metal 3,500','External TCs and gates are the weak ring; keep the main core deep inside.','rust compound tower base build quad'],
['LARGE','ROOFTOP DEFENCE','Trio / Quad','wood 9,000 · stone 32,000 · metal 3,000','Roof peaks help defenders but become a rocket target; split beds and kits.','rust rooftop defence base build'],
['LARGE','BUNKER HONEYCOMB','Trio / Quad','wood 8,500 · stone 29,000 · metal 2,500','The bunker mechanic is powerful but fragile if the entrance or seal is understood.','rust bunker honeycomb base build trio'],
['EXTRA LARGE','FORTRESS 5X5','Quad / Team','wood 16,000 · stone 62,000 · metal 5,500','Size alone is not defence; a straight path to the TC makes this expensive but weak.','rust 5x5 fortress base build team'],
['EXTRA LARGE','MULTI-CORE FORT','Quad / Team','wood 18,000 · stone 70,000 · metal 6,000','Separate cores reduce total loss, while wide roof spans invite top-down raids.','rust multi core team base build'],
['EXTRA LARGE','CLAN COMPOUND','Quad / Team','wood 25,000 · stone 95,000 · metal 8,000','External gates and TCs must be maintained; one neglected section opens the compound.','rust clan compound base build 2026'],
['EXTRA LARGE','HILLSIDE MEGA BASE','Quad / Team','wood 20,000 · stone 82,000 · metal 7,000','The terrain helps conceal the footprint but can expose a single mountain-side wall.','rust hillside mega base build'],
['EXTRA LARGE','ENDGAME DEFENCE GRID','Quad / Team','wood 22,000 · stone 88,000 · metal 7,500','Power, beds and turrets need separated redundancies; one central failure is costly.','rust endgame defence grid clan base build']
].map((x,i)=>({size:x[0],name:x[1],team:x[2],materials:x[3],weak:x[4],query:x[5],img:['combat.jpg','world.jpg','hero.webp','breach.jpg','power.jpg','pasture.jpg','farming.jpg','wildlife.jpg','map.png','new-poster.jpg'][i%10]}));
const videoIds=['XpgNOos-2MY','eB2NxFOBH6A','FbebTwHJaxI','FfSZhUvGteY','098AvO3VbZ0','Zo71HhTp7gU','8BJm7IucCQ0','qDRD0V_zOMI','aHR9eSFBNXM','6ulMibUqWo8','p8_yomfuxE4','-yUW_bCQ6F8','YLW1JQupBco','SZEVmFDgmAQ','0a2SoJs6lq8','4HYOdkeIBTo','iPGeZVX7VVo','LvSM94FdpdI','j7Ntd4oZ5t4','wnp7-SK8lkw'];baseData.forEach((b,i)=>b.videoId=videoIds[i]);
pages.push('bases');names.bases='BASE BUILDING GUIDES';
const link=document.createElement('a');link.dataset.page='bases';link.href='#bases';link.innerHTML='<span>⌂</span> Base building guides';$$('[data-page="raid"]')[0].before(link);
const section=document.createElement('section');section.className='page tools-page';section.hidden=true;section.id='page-bases';section.innerHTML=`<div class="tools-heading"><span class="eyebrow">AUSSIE MAFIA BUILD SCHOOL</span><h1>Build bigger.<br/><em>Stay standing.</em></h1><p>Twenty practical Rust base ideas from small starter builds to extra-large team compounds. Use the estimates as planning guides, then check your live building plan in-game.</p></div><div class="base-notice"><strong>SERVER NOTICE</strong><span>PLAYERS SHOULD PRIORITIZE STRONGER, MORE RESILIENT BASE DESIGNS TO REDUCE OFFLINE RAID LOSSES.</span></div><div class="base-controls"><div class="base-filters" role="group" aria-label="Filter base sizes">${['ALL','SMALL','MEDIUM','LARGE','EXTRA LARGE'].map((x,i)=>`<button class="${i===0?'active':''}" data-base-filter="${x}">${x}</button>`).join('')}</div><label class="upkeep-picker">DAILY UPKEEP RATE<select id="baseUpkeep"><option value="25">25% · Very low</option><option value="50" selected>50% · Aussie Mafia</option><option value="75">75% · Higher protection</option><option value="100">100% · Full estimate</option></select></label></div><div class="upkeep-explainer"><span>ESTIMATE CALCULATOR</span><strong id="upkeepSummary">50% upkeep selected</strong><p>Material figures are rough planning estimates. The calculator scales the stone, metal and HQM-style protection allowance for a 24-hour period; always confirm exact Tool Cupboard upkeep after placing the final build.</p></div><div class="base-grid" id="baseGrid"></div><dialog class="video-dialog" id="baseVideo"><button aria-label="Close tutorial" class="close">×</button><span class="section-label">BUILD TUTORIAL / YOUTUBE</span><h2 id="baseVideoTitle">Watch the build.</h2><div class="video-frame"><iframe id="baseVideoFrame" title="Rust base building tutorial" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture; web-share" allowfullscreen></iframe></div><a class="text-link" id="baseVideoExternal" target="_blank" rel="noopener">OPEN YOUTUBE SEARCH IN A NEW TAB +</a></dialog>`;$('#main').append(section);
const fmt=n=>Math.round(n).toLocaleString('en-AU');const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function upkeepMaterials(m,rate){const parts=m.match(/wood ([\d,]+) · stone ([\d,]+) · metal ([\d,]+)/);if(!parts)return m;const scale=rate/100;return `WOOD ${fmt(Number(parts[1].replaceAll(',',''))*scale)} · STONE ${fmt(Number(parts[2].replaceAll(',',''))*scale)} · METAL ${fmt(Number(parts[3].replaceAll(',',''))*scale)} / 24H`}
function drawBases(filter='ALL'){const rate=Number($('#baseUpkeep').value);$('#upkeepSummary').textContent=rate===50?'50% upkeep selected · Aussie Mafia default':rate+'% upkeep selected';const shown=baseData.filter(b=>filter==='ALL'||b.size===filter);$('#baseGrid').innerHTML=shown.map((b,i)=>`<article class="base-card"><div class="base-image"><img src="https://img.youtube.com/vi/${b.videoId}/hqdefault.jpg" alt="${esc(b.name)} Rust base tutorial thumbnail" loading="lazy"><span>${b.size}</span><b>${String(i+1).padStart(2,'0')}</b></div><div class="base-body"><span class="eyebrow">${b.team}</span><h2>${b.name}</h2><dl><div><dt>BUILD COST</dt><dd>${b.materials.toUpperCase()}</dd></div><div><dt>DAILY UPKEEP · ${rate}%</dt><dd>${upkeepMaterials(b.materials,rate)}</dd></div></dl><p><strong>WEAK POINTS</strong> ${esc(b.weak)}</p><button class="primary base-video" data-video-id="${b.videoId}" data-title="${esc(b.name)}">WATCH BUILD TUTORIAL <b>+</b></button></div></article>`).join('')}
$$('[data-base-filter]').forEach(b=>b.onclick=()=>{$$('[data-base-filter]').forEach(x=>x.classList.toggle('active',x===b));drawBases(b.dataset.baseFilter)});$('#baseUpkeep').onchange=()=>drawBases(document.querySelector('[data-base-filter].active')?.dataset.baseFilter||'ALL');
const baseDialog=$('#baseVideo');const baseFrame=$('#baseVideoFrame');baseFrame.outerHTML='<div id="baseVideoHost"></div>';baseDialog.querySelector('.close').insertAdjacentHTML('afterend','<div class="video-nav"><button class="video-back" id="baseVideoBack">← BACK TO BASE GUIDES</button><span id="baseVideoProgress">PROGRESS SAVED IN THIS BROWSER</span></div><div class="video-controls" aria-label="Video controls"><button id="basePlayPause">PLAY / PAUSE</button><button id="baseRewind">↶ 10 SEC</button><button id="baseForward">10 SEC ↷</button><label>SPEED<select id="baseSpeed"><option value="0.25">0.25×</option><option value="0.5">0.5×</option><option value="0.75">0.75×</option><option value="1" selected>1× NORMAL</option><option value="1.25">1.25×</option><option value="1.5">1.5×</option><option value="2">2×</option></select></label><button id="baseFullscreen">FULL SCREEN</button><button id="baseResetProgress">RESET POSITION</button></div>');
const baseVideoState={player:null,videoId:'',saveTimer:null,resume:0,fullWindow:false,nativeFullscreen:false};const baseProgressKey=id=>'aussieMafiaBaseProgress:'+id;const baseTime=s=>{s=Math.max(0,Math.floor(s||0));return Math.floor(s/60)+':'+String(s%60).padStart(2,'0')};const readBaseProgress=id=>{try{return Number(localStorage.getItem(baseProgressKey(id)))||0}catch{return 0}};const saveBaseProgress=()=>{if(!baseVideoState.player||!baseVideoState.videoId)return;const t=Math.floor(baseVideoState.player.getCurrentTime?.()||0);if(!t)return;try{localStorage.setItem(baseProgressKey(baseVideoState.videoId),String(t))}catch{}$('#baseVideoProgress').textContent='SAVED AT '+baseTime(t)+' · THIS BROWSER'};const stopBasePlayer=save=>{if(save)saveBaseProgress();clearInterval(baseVideoState.saveTimer);baseVideoState.saveTimer=null;try{baseVideoState.player?.destroy()}catch{}baseVideoState.player=null};
const loadYouTubeApi=()=>{if(window.YT?.Player)return Promise.resolve();if(window.__aussieMafiaYouTubeApi)return window.__aussieMafiaYouTubeApi;window.__aussieMafiaYouTubeApi=new Promise(resolve=>{const old=window.onYouTubeIframeAPIReady;window.onYouTubeIframeAPIReady=()=>{old?.();resolve()};const s=document.createElement('script');s.src='https://www.youtube.com/iframe_api';document.head.append(s)});return window.__aussieMafiaYouTubeApi};
async function openBaseVideo(b){stopBasePlayer(true);baseVideoState.videoId=b.dataset.videoId;baseVideoState.resume=readBaseProgress(baseVideoState.videoId);$('#baseVideoTitle').textContent=b.dataset.title+' · build tutorial';$('#baseVideoProgress').textContent=baseVideoState.resume?'RESUMING FROM '+baseTime(baseVideoState.resume)+' · THIS BROWSER':'PROGRESS SAVED IN THIS BROWSER';$('#baseVideoExternal').href='https://www.youtube.com/watch?v='+encodeURIComponent(baseVideoState.videoId);$('#baseVideoExternal').textContent='OPEN THIS TUTORIAL ON YOUTUBE +';$('#baseVideoHost').innerHTML='';baseDialog.showModal();await loadYouTubeApi();if(!baseVideoState.videoId)return;baseVideoState.player=new YT.Player('baseVideoHost',{host:'https://www.youtube-nocookie.com',videoId:baseVideoState.videoId,playerVars:{controls:1,fs:1,playsinline:1,rel:0,modestbranding:1,origin:location.origin,start:baseVideoState.resume},events:{onReady:e=>{const frame=e.target.getIframe?.();if(frame){frame.setAttribute('allow',(frame.getAttribute('allow')||'')+'; fullscreen');frame.setAttribute('allowfullscreen','true');frame.allowFullscreen=true}baseVideoState.saveTimer=setInterval(saveBaseProgress,3000);if(baseVideoState.resume)e.target.seekTo(baseVideoState.resume,true)},onStateChange:e=>{if(e.data===YT.PlayerState.PAUSED||e.data===YT.PlayerState.ENDED)saveBaseProgress()},onError:e=>{$('#baseVideoProgress').textContent='THIS YOUTUBE TUTORIAL IS CURRENTLY UNAVAILABLE · TRY ANOTHER GUIDE'}}})}
const getBaseFullscreenElement=()=>document.fullscreenElement||document.webkitFullscreenElement;const syncBaseFullscreenButton=()=>{const active=Boolean(getBaseFullscreenElement()||baseVideoState.fullWindow);$('#baseFullscreen').textContent=active?'EXIT FULL SCREEN':'FULL SCREEN';$('#baseFullscreen').setAttribute('aria-pressed',String(active))};const setBaseFullWindow=active=>{baseVideoState.fullWindow=active;baseDialog.classList.toggle('video-fullwindow',active);document.documentElement.classList.toggle('base-video-no-scroll',active);document.body.classList.toggle('base-video-no-scroll',active);syncBaseFullscreenButton()};const exitBaseFullscreen=()=>{const exit=document.exitFullscreen||document.webkitExitFullscreen;if(exit){try{const result=exit.call(document);if(result?.catch)result.catch(()=>{})}catch{}}};const requestBaseFullscreen=()=>{const stage=document.querySelector('#baseVideo .video-frame');if(getBaseFullscreenElement()){exitBaseFullscreen();setBaseFullWindow(false);return}if(baseVideoState.fullWindow){setBaseFullWindow(false);return}setBaseFullWindow(true);const request=stage?.requestFullscreen||stage?.webkitRequestFullscreen;if(request){try{const result=request.call(stage,{navigationUI:'hide'});if(result?.catch)result.catch(()=>{})}catch{}}};
const closeBaseVideo=()=>{setBaseFullWindow(false);if(getBaseFullscreenElement())exitBaseFullscreen();baseDialog.close()};$('#baseGrid').addEventListener('click',e=>{const b=e.target.closest('.base-video');if(b)openBaseVideo(b)});$('#baseVideoBack').onclick=closeBaseVideo;baseDialog.querySelector('.close').onclick=closeBaseVideo;baseDialog.addEventListener('close',()=>{setBaseFullWindow(false);if(getBaseFullscreenElement())exitBaseFullscreen();stopBasePlayer(true)});$('#basePlayPause').onclick=()=>{const p=baseVideoState.player;if(!p)return;const state=p.getPlayerState();state===YT.PlayerState.PLAYING?p.pauseVideo():p.playVideo()};$('#baseRewind').onclick=()=>{const p=baseVideoState.player;if(p)p.seekTo(Math.max(0,p.getCurrentTime()-10),true)};$('#baseForward').onclick=()=>{const p=baseVideoState.player;if(p)p.seekTo(p.getCurrentTime()+10,true)};$('#baseSpeed').onchange=e=>{const p=baseVideoState.player;if(p)p.setPlaybackRate(Number(e.target.value))};$('#baseFullscreen').onclick=requestBaseFullscreen;const syncNativeFullscreen=()=>{const active=getBaseFullscreenElement();if(active)baseVideoState.nativeFullscreen=true;else if(baseVideoState.nativeFullscreen){baseVideoState.nativeFullscreen=false;setBaseFullWindow(false)}syncBaseFullscreenButton()};document.addEventListener('fullscreenchange',syncNativeFullscreen);document.addEventListener('webkitfullscreenchange',syncNativeFullscreen);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&baseVideoState.fullWindow&&!getBaseFullscreenElement())setBaseFullWindow(false)});$('#baseResetProgress').onclick=()=>{try{localStorage.removeItem(baseProgressKey(baseVideoState.videoId))}catch{}baseVideoState.resume=0;$('#baseVideoProgress').textContent='POSITION RESET · START FROM THE BEGINNING';baseVideoState.player?.seekTo(0,true)};
const guideStyle=document.createElement('style');guideStyle.textContent=`.base-notice{display:flex;gap:18px;align-items:center;padding:18px 22px;margin:20px 0 26px;border-left:3px solid var(--red);background:#121e2ee8;letter-spacing:.5px}.base-notice strong{color:#ee7770;font-size:11px;letter-spacing:1.5px}.base-notice span{font-size:13px}.base-controls{display:flex;gap:20px;align-items:end;justify-content:space-between;margin-bottom:18px}.base-filters{display:flex;gap:8px;flex-wrap:wrap}.base-filters button,.upkeep-picker select{border:1px solid #ffffff2b;background:#172538;color:#e8eef5;padding:12px 14px;font:inherit;font-size:12px;letter-spacing:.5px}.base-filters button.active,.base-filters button:hover{background:#ee7770;color:#111923;border-color:#ee7770}.upkeep-picker{min-width:220px;color:#b8c3ce;font-size:11px;letter-spacing:1px}.upkeep-picker select{display:block;width:100%;margin-top:7px;font-size:14px}.upkeep-explainer{padding:20px 22px;margin-bottom:24px;background:#0c1725e8;border:1px solid #ffffff20}.upkeep-explainer span{font-size:10px;color:#ee9690;letter-spacing:1.5px}.upkeep-explainer strong{display:block;font:700 25px 'Barlow Condensed',sans-serif;margin:5px 0}.upkeep-explainer p{font-size:13px;color:#aebaca;max-width:900px}.base-grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:22px}.base-card{background:#121e2ef2;border:1px solid #ffffff20;border-radius:5px;overflow:hidden}.base-image{height:190px;position:relative;background:#17202b}.base-image img{width:100%;height:100%;object-fit:cover;filter:saturate(.8) contrast(1.06)}.base-image:after{content:'';position:absolute;inset:0;background:linear-gradient(transparent 35%,#07111ddd)}.base-image span,.base-image b{position:absolute;z-index:1;bottom:16px}.base-image span{left:20px;color:#f1aaa4;font-size:10px;letter-spacing:1.5px}.base-image b{right:20px;font:700 32px 'Barlow Condensed',sans-serif;color:#fff}.base-body{padding:22px}.base-body h2{font-size:29px;margin:9px 0 17px}.base-body dl{margin:0 0 18px}.base-body dl>div{padding:10px 0;border-bottom:1px solid #ffffff14}.base-body dt{color:#ee9690;font-size:10px;letter-spacing:1px}.base-body dd{margin:5px 0 0;color:#dae2ec;font-size:12px;line-height:1.5}.base-body p{font-size:13px;color:#b8c3ce;line-height:1.55;min-height:62px}.base-body p strong{color:#f1aaa4;font-size:10px;letter-spacing:1px}.base-video{width:100%;font-size:11px;padding:12px}.video-dialog{width:min(900px,92vw);background:#101b29f8;color:#eef3f8;border:1px solid #ffffff2b;padding:24px}.video-frame{aspect-ratio:16/9;background:#05080d;margin:20px 0}.video-frame iframe{width:100%;height:100%;border:0}.video-dialog .text-link{font-size:12px}@media(max-width:800px){.base-controls{display:block}.upkeep-picker{display:block;margin-top:18px}.base-grid{grid-template-columns:1fr}.base-notice{display:block}.base-notice span{display:block;margin-top:8px}}`;document.head.append(guideStyle);drawBases();route();
const baseControlStyle=document.createElement('style');baseControlStyle.textContent='.video-nav{display:flex;align-items:center;justify-content:space-between;gap:14px;margin:16px 0 0}.video-back{background:transparent;border:1px solid #ffffff30;color:#eef3f8;padding:10px 12px;font:inherit;font-size:11px;letter-spacing:.6px}.video-back:hover{background:#ee7770;color:#111923;border-color:#ee7770}.video-nav span{font-size:10px;color:#eeaaa5;letter-spacing:.8px;text-align:right}.video-controls{display:flex;align-items:center;gap:8px;flex-wrap:wrap;margin:14px 0}.video-controls button,.video-controls select{background:#18283a;border:1px solid #ffffff25;color:#eef3f8;padding:9px 10px;font:inherit;font-size:10px;letter-spacing:.4px}.video-controls button:hover,.video-controls select:hover{border-color:#ee7770;background:#25384d}.video-controls label{display:flex;align-items:center;gap:5px;color:#eeaaa5;font-size:10px;letter-spacing:.8px}.video-controls select{padding:9px 7px}.video-frame>div{width:100%;height:100%;min-height:180px}.video-frame iframe{width:100%;height:100%;min-height:180px;border:0}@media(max-width:640px){.video-nav{align-items:flex-start;flex-direction:column}.video-nav span{text-align:left}.video-controls{gap:6px}.video-controls button,.video-controls select{font-size:9px;padding:8px}.video-frame{margin:14px 0}}';document.head.append(baseControlStyle);
const fullscreenStyle=document.createElement('style');fullscreenStyle.textContent='html.base-video-no-scroll,html.base-video-no-scroll body{overflow:hidden!important;overscroll-behavior:none!important}#baseVideo.video-fullwindow[open]{position:fixed!important;inset:0!important;width:100vw!important;max-width:none!important;height:100dvh!important;max-height:none!important;margin:0!important;padding:clamp(12px,3vw,28px)!important;background:#060b12!important;border:0!important;border-radius:0!important;z-index:2147483000!important;overflow:auto!important;display:flex!important;flex-direction:column!important}#baseVideo.video-fullwindow[open] .video-frame{flex:1 1 auto;min-height:180px;height:auto;aspect-ratio:auto;margin:16px 0;background:#000}#baseVideo.video-fullwindow[open] .video-frame>div,#baseVideo.video-fullwindow[open] .video-frame iframe{height:100%;min-height:0}#baseVideo .video-frame:fullscreen{width:100vw;height:100vh;margin:0;background:#000;display:flex;align-items:center;justify-content:center;border:0;border-radius:0}#baseVideo .video-frame:fullscreen>div,#baseVideo .video-frame:fullscreen iframe{width:100%;height:100%;min-height:0}#baseVideo .video-frame:-webkit-full-screen{width:100vw;height:100vh;margin:0;background:#000}';document.head.append(fullscreenStyle);
})();
