(()=>{'use strict';
const data=window.WEAPONS||[],e=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cat=w=>w.id.startsWith('weapon.mod.')?'Attachments':/bow|crossbow|blowpipe|nailgun/.test(w.id)?'Bows & primitive':/launcher|speargun/.test(w.id)?'Launchers':/hmlmg|lmg|^minigun/.test(w.id)?'Machine guns':/smg/.test(w.id)?'SMGs':/shotgun/.test(w.id)?'Shotguns':/pistol|revolver/.test(w.id)?'Pistols':/^rifle/.test(w.id)?'Rifles':/grenade|knife|spear|club|sword|machete|cleaver|boomerang|paddle|pitchfork|stake|snowball$/.test(w.id)?'Throwables & melee':'Siege & special';
const roles={'Bows & primitive':'Early-game projectile weapons. Account for travel time and reload or draw time.','Pistols':'A compact option for short encounters or as a backup.','SMGs':'Automatic fire suited to closer engagements; use controlled bursts as distance increases.','Rifles':'Compare ammunition speed and damage for your intended fighting distance.','Machine guns':'Sustained fire and suppression; manage recoil and exposure.','Shotguns':'Close-range pellet weapons; slugs trade a pellet cloud for one projectile.','Launchers':'Specialist ammunition for explosives, anti-aircraft or underwater use.','Throwables & melee':'Close combat and thrown weapons; effects depend on the item.','Siege & special':'Specialist equipment with its own operating rules.','Attachments':'Fit only to compatible weapons; check the trade-offs before choosing.'};
let chosen=data.find(w=>w.id==='rifle.ak')||data[0];
const tips={
'weapon.mod.holosight':'A useful starting choice for a clear close-to-medium-range sight picture.',
'weapon.mod.lasersight':'Consider it when you want tighter aim and reduced sway; its beam can reveal your position.',
'weapon.mod.small.scope':'Consider magnification for longer shots. Test the recoil and narrower view before close fighting.',
'weapon.mod.8x.scope':'A long-range option; magnification does not remove bullet drop or recoil.',
'weapon.mod.extendedmags':'Useful when reload interruptions matter. More capacity does not improve shot placement.',
'weapon.mod.muzzlebrake':'An option for recoil control, with damage and accuracy trade-offs. Try it against a wall before a fight.',
'weapon.mod.muzzleboost':'Trades precision for a faster firing cycle; evaluate it for short-range fights.',
'weapon.mod.silencer':'Useful when quieter fire matters; lower damage and velocity are meaningful costs.',
'weapon.mod.oilfiltersilencer':'A quieter-fire option with damage, velocity and durability costs.',
'weapon.mod.sodacansilencer':'An improvised quieter-fire option; check its damage, velocity and durability costs.',
'weapon.mod.burstmodule':'Consider controlled bursts if the weapon accepts it. Compare handling with normal fire.',
'weapon.mod.flashlight':'Useful for dark interiors, but illumination reveals where you are aiming.',
'weapon.mod.simplesight':'A low-cost sight option; compare the sight picture with the weapon’s iron sights.',
'weapon.mod.targetingattachment':'Useful for marking targets for your group.',
'weapon.mod.gascompressionovedrive':'Trades extra damage and velocity against handling and firing-cycle changes.'};
function select(w){chosen=w;renderDetail();document.querySelectorAll('[data-weapon-id]').forEach(b=>{b.classList.toggle('selected',b.dataset.weaponId===w.id);b.setAttribute('aria-pressed',String(b.dataset.weaponId===w.id))})}
function renderList(){let q=e('#weapon-search').value.toLowerCase(),c=e('#weapon-category').value;let a=data.filter(w=>(c==='all'||cat(w)===c)&&(w.name+' '+w.id+(w.id==='lmg.m249'?' M2':'')).toLowerCase().includes(q)).sort((a,b)=>a.name.localeCompare(b.name));e('#weapon-count').textContent=a.length+' items';e('#weapon-list').innerHTML=a.length?a.map(w=>`<button data-weapon-id="${esc(w.id)}" class="weapon-choice ${chosen?.id===w.id?'selected':''}" aria-pressed="${chosen?.id===w.id}"><img src="${esc(w.image)}" alt="" loading="lazy"><span>${esc(w.name)}<small>${esc(cat(w))}</small></span></button>`).join(''):'<p>No matching items. Try another name or category.</p>';e('#weapon-list').querySelectorAll('button').forEach(b=>b.onclick=()=>select(data.find(x=>x.id===b.dataset.weaponId)))}
function renderDetail(){if(!chosen)return;let w=chosen,c=cat(w),ammo=w.ammo||[],mods=w.mods||[],isMod=c==='Attachments',compatible=isMod?data.filter(x=>(x.mods||[]).some(m=>m[0]===w.name)):[];
let head=`<div class="weapon-hero"><img src="${esc(w.image)}" alt="${esc(w.name)} in-game item"><div><span class="eyebrow">${esc(c)}</span><h2>${esc(w.name)}${w.id==='lmg.m249'?' <small>(M2)</small>':''}</h2><p>${esc(w.note||roles[c])}</p></div></div>`;
let rows=ammo.map(a=>`<tr><th scope="row">${esc(a[0])}</th><td>${esc(a[1])}</td><td>${esc(a[3])}</td><td>${esc(a[4])}</td></tr>`).join('');
let body=ammo.length?`<h3>Ammunition comparison</h3><div class="armory-table"><table><thead><tr><th>Ammo</th><th>Listed damage</th><th>Speed (m/s)</th><th>Headshot</th></tr></thead><tbody>${rows}</tbody></table></div><p class="armory-note">Base wiki values before armour, range and attachments. Shotgun figures are per pellet. Fire/explosion effects are not a guaranteed total hit. *Not captured means this table omits explosive damage, not that the ammunition does zero damage.</p>`:'<p class="armory-note">No ammunition damage table is published in the source for this item. See its item reference for operating details.</p>';
if(isMod){body=`<h3>When to consider it</h3><p>${esc(tips[w.id]||'Compare its effects with the alternatives for the same attachment slot.')}</p><h3>Compatible weapons &amp; effects</h3>`+compatible.map(x=>`<button class="compatible-link" data-open="${esc(x.id)}"><img src="${esc(x.image)}" alt=""><span>${esc(x.name)}<small>${esc(x.mods.find(m=>m[0]===w.name)?.[1]||'See source')}</small></span></button>`).join('');if(!compatible.length)body+='<p>Compatibility details have not been verified in the retrieved weapon pages.</p>'}
else{body+='<h3>Compatible attachments</h3>';body+=mods.length?mods.map(m=>{let a=data.find(x=>x.name===m[0]);return `<div class="attachment-row">${a?`<button data-open="${esc(a.id)}"><img src="${esc(a.image)}" alt="${esc(a.name)}"></button>`:''}<div><strong>${esc(m[0])}</strong><p>${esc(m[1])}</p>${a?`<small>${esc(tips[a.id]||'Check the item reference for details.')}</small>`:''}</div></div>`}).join(''):'<p>No compatible attachments listed in the source.</p>';
if(['Pistols','SMGs','Rifles','Machine guns','Shotguns'].includes(c)){body+='<h3>Recoil &amp; control</h3><p>Exact current-version mouse-path measurements are not available in this guide. No fixed recoil pattern is shown. Test this weapon with your sensitivity, stance and attachments; use shorter bursts or paced shots as distance increases.</p>'}
body+='<h3>Range &amp; bullet drop</h3><p>Use the ammunition speed above to compare travel time. Precise drop and damage-falloff curves have not been verified here. Practise at known distances with the ammunition and sight you intend to use.</p>'}
e('#weapon-detail').innerHTML=head+body+`<a class="text-link" href="${esc(w.source)}" target="_blank" rel="noopener">ITEM DATA · SOURCE</a>`;e('#weapon-detail').querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>select(data.find(x=>x.id===b.dataset.open)))}
e('#weapon-search').addEventListener('input',renderList);e('#weapon-category').addEventListener('change',renderList);renderList();renderDetail();})();
